accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from accounts import views
from django.urls import path



app_name='accounts'

urlpatterns = [
    path('password_reset/', auth_views.PasswordResetView.as_view(), {'template_name': "registration/password_reset_form.html"}, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView,{'template_name': "registration/password_reset_done.html"},name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView,{'template_name': "registration/password_reset_confirm.html"},name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView,{'template_name': "registration/password_reset_complete.html"},name='password_reset_complete'),
    url(r'^signup/$', views.signup, name='signup'),
    path('show_data/', views.show_data, name='show_data'),
    path('pass_value/', views.pass_value, name='pass_value'),
    path('home/',views.Homepage.as_view(),name='home'),
    path('fetch_data/', views.fetch_data, name='fetch_data'),
    path('add_batch/',views.AddBatch.as_view(),name='add_batch'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'logout/$',auth_views.LogoutView.as_view(next_page='index'),name = 'logout'),    
]

time_table/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from accounts import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.CustomLoginView.as_view(),name='index'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('account/',include('django.contrib.auth.urls')),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models
from resource_data.models import Course, Teacher
from django.contrib.auth.models import AbstractUser
from django.core import validators
# Create your models here.
class User(AbstractUser):
    """
    A model for all type of users
    """

    is_locked = models.BooleanField(default=False)
    phone_no = models.CharField(max_length=13)

    def __str__(self):
        return self.first_name+" "+self.last_name

class Result(models.Model):
    cse1 = models.CharField(blank=True, default='0', null=True,max_length=10)
    cse2 = models.CharField(blank=True, default='0', null=True,max_length=10)
    cse3 = models.CharField(blank=True, default='0', null=True,max_length=10)
    cse4 = models.CharField(blank=True, default='0', null=True,max_length=10)
    cse5 = models.CharField(blank=True, default='0', null=True,max_length=10)
    cse6 = models.CharField(blank=True, default='0', null=True,max_length=10)
    cse7 = models.CharField(blank=True, default='0', null=True,max_length=10)
    cse8 = models.CharField(blank=True, default='0', null=True,max_length=10)
    ece1 = models.CharField(blank=True, default='0', null=True,max_length=10)
    ece2 = models.CharField(blank=True, default='0', null=True,max_length=10)
    ece3 = models.CharField(blank=True, default='0', null=True,max_length=10)
    ece4 = models.CharField(blank=True, default='0', null=True,max_length=10)
    ece5 = models.CharField(blank=True, default='0', null=True,max_length=10)
    ece6 = models.CharField(blank=True, default='0', null=True,max_length=10)
    ece7 = models.CharField(blank=True, default='0', null=True,max_length=10)
    ece8 = models.CharField(blank=True, default='0', null=True,max_length=10)
    it1 = models.CharField(blank=True, default='0', null=True,max_length=10)
    it2 = models.CharField(blank=True, default='0', null=True,max_length=10)
    it3 = models.CharField(blank=True, default='0', null=True,max_length=10)
    it4 = models.CharField(blank=True, default='0', null=True,max_length=10)
    it5 = models.CharField(blank=True, default='0', null=True,max_length=10)
    it6 = models.CharField(blank=True, default='0', null=True,max_length=10)
    it7 = models.CharField(blank=True, default='0', null=True,max_length=10)
    it8 = models.CharField(blank=True, default='0', null=True,max_length=10)

    class Meta:
        ordering = ['id']


class ResultTeacher(models.Model):
    cse1_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    cse2_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    cse3_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    cse4_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    cse5_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    cse6_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    cse7_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    cse8_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    ece1_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    ece2_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    ece3_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    ece4_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    ece5_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    ece6_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    ece7_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    ece8_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    it1_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    it2_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    it3_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    it4_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    it5_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    it6_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    it7_faculty = models.CharField(blank=True, default='', null=True,max_length=10)
    it8_faculty = models.CharField(blank=True, default='', null=True,max_length=10)

    class Meta:
        ordering = ['id']

class Batch(models.Model):
    """
    It contains information about a class.How many subjects are,
    who are going to teach them,etc.
    """
    branch_sem = models.CharField(max_length=10)
    course_code = models.ForeignKey(Course, on_delete=models.CASCADE,)
    teacher_code = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    room = models.CharField(max_length=10)
    no_class_week = models.IntegerField()
    no_of_slots = models.IntegerField()
    course_schema = models.IntegerField(validators=[validators.MinValueValidator(2010), validators.MaxValueValidator(9999)])


    def __str__(self):
        return str(self.course_code)+' '+str(self.branch_sem)

    class Meta:
        unique_together = (("branch_sem", "course_code"),)

resource_data/models.py
from django.db import models
from django.core import validators
# Create your models here.

class Branch(models.Model):
    """
        It contain information about branches.
    """
    branch_code = models.CharField(max_length=10, primary_key=True)
    branch_name = models.CharField(max_length=200)


    def __str__(self):
        return self.branch_code

class Teacher(models.Model):
    """
        This defines the relation table Teacher. It contains required information about teacher.
    """
    teacher_code = models.CharField(max_length=10, primary_key = True)

    first_name = models.CharField(max_length=200)

    last_name = models.CharField(max_length=200)

    department = models.ForeignKey(Branch, on_delete=models.CASCADE)

    class Meta:
        ordering = ('first_name',)

    def __str__(self):
        return self.teacher_code

class Course(models.Model):
    """
        It contains the course details.
    """
    course_code = models.CharField(max_length=10, primary_key = True)
    course_name = models.CharField(max_length=200)
    branch_code = models.ForeignKey(Branch, on_delete=models.CASCADE)
    sem = models.IntegerField()
    credits = models.IntegerField(default=3, validators=[validators.MinValueValidator(0), validators.MaxValueValidator(10)])
    lecture = models.IntegerField(default=0, validators=[validators.MinValueValidator(0), validators.MaxValueValidator(10)])
    tutorial = models.IntegerField(default=0, validators=[validators.MinValueValidator(0), validators.MaxValueValidator(10)])
    practical = models.IntegerField(default=0,validators=[validators.MinValueValidator(0), validators.MaxValueValidator(10)])
    course_intro = models.IntegerField(validators=[validators.MinValueValidator(2010), validators.MaxValueValidator(9999)])

    class Meta:
        ordering = ('sem','course_code')

    def __str__(self):
        return self.course_code

class Room(models.Model):
    room_no = models.CharField(max_length=15,primary_key=True)
    def __str__(self):
        return self.room_no

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth import get_user_model, authenticate
# from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from accounts import models
from django.utils.translation import ugettext_lazy as _
import unicodedata

class LoginForm(AuthenticationForm):
    """
    This form is linked with model User, it determines the fields in log in page
    """
    model = models.User
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = "Email"

class SignupForm(UserCreationForm):
    """
    it determines the fields in  sign up page
    """

    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = models.User
        fields = ('first_name','last_name', 'phone_no', 'email', 'password1', 'password2')

    def clean_email(self):
        """
        Checks if email is already in use
        """
        email = self.cleaned_data.get('email')

        if email in models.User.objects.all().values_list('email', flat=True) or email in models.User.objects.all().values_list('email', flat=True):
            raise forms.ValidationError(_("This email address is already in use. Please supply a different email address."))
        return email
    # def clean_address(self):
    #     address = self.cleaned_data.get('address')
    #     if 'save_as_draft' in self.data:
    #         return address
    #     elif 'submit_application' in self.data:
    #         if (address == ''):
    #             raise forms.ValidationError(_("Address is required"))
    #         return address

accounts/templates/accounts/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration in IIIT Una Timetable Generator portal:

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/active_done.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% load staticfiles %}
{% bootstrap_javascript jquery='full' %}

{% block title %}
Password Reset Done
{% endblock %}

{% block body %}

<br><br>

<div class="container">
  <p>
    Thank you for your email confirmation. Now you can <a href="{% url 'index' %}">Log in</a> your account.
  </p>
</div>


{% endblock %}

accounts/templates/accounts/add_batch.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% load staticfiles %}
{% bootstrap_javascript jquery='full' %}

{% block title %}
sign up
{% endblock %}

{% block body %}
{% if user.is_authenticated %}
  <div class="container"  style="background-color: #F2F3F4; border-radius: 5px; border-color: grey;"><br>
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <font style="font-size: 25px; font-family: Helvetica;">Add batch</font><hr>
        </div>
      </div>
    </div>
  </div><br>
    <div class="container">
      <form action="{% url 'accounts:add_batch' %}" method = "POST">
        {% csrf_token %}
        {% for course in courses %}
        <div>
          <div class="row">
            <div class="form-group col-md-6">
              <select name="course_code{{forloop.counter}}" class="form-control" id="id_course_code{{forloop.counter}}">
                <option value="{{course.course_code}}">{{course.course_name}}({{course.course_code}})</option>
                {% for c in cc %}
                <option value="{{c.course_code}}">{{c.course_name}}({{c.course_code}})</option>
                {% endfor %}
              </select>
            </div>
            <div class="form-group col-md-6">
              <select name="teacher_code{{forloop.counter}}" class="form-control" id="id_teacher{{forloop.counter}}">
                <option value="">Teacher</option>
                {% for teacher in teachers %}
                <option value="{{teacher.teacher_code}}">{{teacher.first_name}} {{teacher.last_name}}({{teacher.teacher_code}})</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="row">
          <div class="form-group col-md-4">
            <select name="room{{forloop.counter}}" class="form-control" id="id_room{{forloop.counter}}">
              <option value="">Select</option>
              {% for room in rooms %}
              <option value="{{room}}">{{room}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group col-md-4">
            <input type="number" name="no_class_week{{forloop.counter}}" class="form-control" placeholder="No of class week" title="" required="" id="id_no_class_week{{forloop.counter}}">
          </div>
          <div class="form-group col-md-4">
            <input type="number" name="no_of_slots{{forloop.counter}}" class="form-control" placeholder="No of slots" title="" required="" id="id_no_of_slots{{forloop.counter}}">
          </div>
          </div>
        </div><hr>
        {% endfor %}
         <input type="hidden" id="id_no_of_courses" name="no_of_courses" value="{{courses.count}}">
         <input type="hidden" id="id_branch_sem" name="branch_sem" value="{{branch_sem}}">
         <input type="hidden" id="id_course_schema" name="course_schema" value="{{course_schema}}">
        <input type="submit" class="btn btn-primary" value="Add">
        <br><br>
      </form>
    </div>


  {% endif %}

{% endblock %}

accounts/templates/accounts/home.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% load staticfiles %}
{% bootstrap_javascript jquery='full' %}
{% block extrascript %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/util.css' %}">
{% endblock %}

{% block title %}
Home
{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-6 limiter">
      <div class="container-table100">
        <div class="wrap-table100">
          <div class="table100 ver1 m-b-110">
            <div class="table100-head">
              <table>
                <thead>
                  <tr class="row100 head">
                    <th style="text-align: center; vertical-align: middle;" class="cell100 column2">S.No</th>
                    <th style="text-align: center; vertical-align: middle;" class="cell100 column2">Batch</th>
                    <th style="text-align: center; vertical-align: middle;" class="cell100 column2">Courses</th>
                  </tr>
                </thead>
              </table>
            </div>

            <div class="table100-body">
              <table>
                <tbody>
                  {% for batch_count in batch_counts %}
                  <tr class="row100 body">
                    <td style="text-align: center; vertical-align: middle;" class="cell100 column2">{{ forloop.counter }}</td>
                    <td style="text-align: center; vertical-align: middle;" class="cell100 column2">{{batch_count.branch_sem}}</td>
                    <td style="text-align: center; vertical-align: middle;" class="cell100 column2">{{batch_count.total}}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 container">
      <br>
      <br>
      <center><h1>ADD BATCH</h1></center>
      <form action="{% url 'accounts:add_batch' %}" method = "GET">
        <div class="">
              <div class="form-group"><label for="id_branch">Branch</label><select required name="branch" class="form-control" id="branch">
                <option value="">Select</option>
                {% for branch in branches %}
                <option value="{{branch.branch_code}}">{{branch.branch_code}}</option>
                {% endfor %}
                </select>
              </div>

              <div class="form-group"><label for="id_sem">Sem</label><select required name="sem" class="form-control" id="id_sem"">
                <option value="">Select</option>
                {% for i in '12345678'|make_list %}
                  <option value="{{forloop.counter}}">{{forloop.counter}}</option>
                {% endfor %}
                </select>
              </div>

              <div class="form-group">
                <label for="id_course_schema">Course Schema</label>
                  <div class="form-group">
                    <select required name="course_schema" class="form-control" id="id_course_schema">
                      <option value="">Course Intro year</option>
                      {% for year in course_schema %}
                      <option value="{{year}}">{{year}}</option>
                      {% endfor %}
                      </select>
                  </div>
              </div>

              <div class="form-group">
                <center>
                  <input type="submit" name='search' class="btn btn-primary " value=" Add ">
                </center>
              </div>
        </div>
      </form>
    </div>
    <div class="col-md-1"></div>
    <!-- <div class="col-md-3">
    </div> -->
  </div>

  <form action="{% url 'accounts:pass_value' %}" method = "GET">
    <div class="container">
      <div class="container row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <div class="form-group ">
            <select required multiple name="batches" class="form-control" id="id_batches">
              <option value="">Select Batches</option>
              {% for batch_count in batch_counts %}
              <option value="{{batch_count.branch_sem}}">{{batch_count.branch_sem}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
              <input type="submit" name='search' class="btn btn-primary " value="Generate Table">
          </div>
        </div>
      </div><hr>
    </div>
  </form>




{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% load staticfiles %}
{% bootstrap_javascript jquery='full' %}

{% block extrascript %}
  <script>
    function redirect(){
      window.location.href = '{% url 'accounts:signup' %}'
    };
  </script>
{% endblock %}

{% block title %}
login
{% endblock %}

{% block body %}
  <div class="register">
    <div class="row">

      <div class="col-md-3 register-left">
        <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
        <h3><font color="white">Welcome</font></h3>
        <p>You are 30 seconds away from from making timetable</p>
        <input type="submit" onclick="redirect()" href="" value="Register"/>
      </div>

      <div class="col-md-9 register-right">
        <div class="tab-content" id="myTabContent">
          <div id="home" role="tabpanel" aria-labelledby="home-tab">
            <h3 class="register-heading">Login as a faculty</h3>
            <form action="{% url 'index' %}" method = "POST">
              {% csrf_token %}
              {% bootstrap_form_errors form %}
              <div class="row register-form">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" name="username" autofocus="" class="form-control" placeholder="Email" title="" required="" id="id_username">
                  </div>
                  <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="Password" title="" required="" id="id_password">
                  </div>
                  <input type="submit" class="btnRegister"  value="Login"/>
                  <a href="{% url 'accounts:password_reset' %}"><font color="blue">Forgot Password?</font></a>
                </div>
                <div class="col-md-3"></div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}










{% block custom_js %}
  <script src="{% static 'js/jquery.easing.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="{% static 'js/contactform.js' %}"></script>
{% endblock %}

accounts/templates/accounts/new.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% load staticfiles %}
{% bootstrap_javascript jquery='full' %}

{% block extrascript %}
  <script src="{% static 'js/function.js' %}"></script>
{% endblock %}
{% block title %}
sign up
{% endblock %}

{% block body %}

<script type="text/javascript">
  var course = {{ course|safe }};
  var teacher = {{ teacher|safe }};
  function timeTable()
  {
    var v1 = Module['vec']();

    var v2 = Module['vec']();

    var v3 = Module['vec']();

    var v4 = Module['vec']();
    var v6 = Module['vec']();

    var v4 = Module['vec_int']();

    var v5 = Module['vec_int']();


    for(var i=0; i < course.length; i++ ){
        v1.push_back(course[i][0]);
        v2.push_back(course[i][1]);
        v6.push_back(course[i][2]);
        v3.push_back(course[i][3]);
        v4.push_back(parseInt(course[i][4]));
        v5.push_back(parseInt(course[i][5]));}

    var getCourse = Module['getCourse'](v1, v2, v3, v4, v5);
    var getTeacher = Module['getTeacher'](v2, v6);

    var ttbl = Module['returnMapData'](getCourse, getTeacher);


      var obj = JSON.parse('{ "name":"John", "age":30, "city":"New York"}');

      // Stores unique branch codes
      var uniqueBranch = new Set();
      for(var i=0; i < course.length; i++)
        uniqueBranch.add(course[i][0]);

      var itr = uniqueBranch.entries();
      var result = {}
      for(var i=0; i<uniqueBranch.size; i++)
      {
        var branch = itr.next().value[0];
        var temp = [];

        var res_temp = ttbl.get(branch);
        var len = res_temp.size();
        for(var j=0; j < len; j++)
          temp[j] = res_temp.get(j);

        result[branch] = JSON.stringify(temp);
      }
      result = JSON.stringify(result);
      console.log(result);

      // var sr = [];
      // for(var i=0; i<)
      // console.log(course);
      // data['key1'] = JSON.stringify(data['key1'])
      // data['key2'] = JSON.stringify(data['key2'])
      obj = JSON.stringify(obj);
      console.log(obj);
      $.ajax({type: 'POST',
                   url: '{% url 'accounts:fetch_data' %}',                            // some data url
                   data: {param: result,csrfmiddlewaretoken: '{{ csrf_token }}'},       // some params
                   success: function (response) {
                           if (response.success) {
                             console.log('Successful');
                             // window.location.href = response.url;
                           }
                           else {
                             console.log('Unsuccesful');
                           }
                   }
                  });
                }

  function redirect(){
    window.location.href = '{% url 'accounts:home' %}'
  };
</script>

<div class="register">
  <div class="row">

    <div class="col-md-3 register-left">
      <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
      <h3><font color="white">Welcome</font></h3>
      <p>You are 30 seconds away from from making timetable</p>
      <input type="submit" onclick="redirect()" href="" value="Home"/>
    </div>

    <div class="col-md-9 register-right">
      <div class="tab-content" id="myTabContent">
        <div id="home" role="tabpanel" aria-labelledby="home-tab">
          <h3 class="register-heading">Select a Batch</h3>
          <form action="{% url 'accounts:show_data' %}" method = "GET">
            <div class="row register-form">
              <div class="col-md-3"></div>
              <div class="col-md-6">
                <div class="form-group ">
                  <select required name="batch" class="form-control" id="id_batch">
                    <option value="">Select Batch</option>
                    {% for batch in all_batches %}
                    <option value="{{batch.branch_sem}}">{{batch.branch_sem}}</option>
                    {% endfor %}
                  </select>
                </div>
                <input onclick="timeTable()" type="submit" name='search' class="btnRegister" value="Show Table">
              </div>
              <div class="col-md-3"></div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% load staticfiles %}
{% bootstrap_javascript jquery='full' %}

{% block extrascript %}
  <script>
    function redirect(){
      window.location.href = '{% url 'index' %}'
    };
  </script>
{% endblock %}

{% block title %}
sign up
{% endblock %}

{% block body %}
  <div class="register">
    <div class="row">

      <div class="col-md-3 register-left">
        <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
        <h3>Welcome</h3>
        <p>You are 30 seconds away from from making timetable</p>
        <input type="submit" onclick="redirect()" href="" value="Login"/><br/>
      </div>

      <div class="col-md-9 register-right">
        <div class="tab-content" id="myTabContent">
          <div id="home" role="tabpanel" aria-labelledby="home-tab">
            <h3 class="register-heading">Sign up as a faculty</h3>
            <form action="{% url 'accounts:signup' %}" method = "POST">
              {% csrf_token %}
              {% bootstrap_form_errors form %}
              <div class="row register-form">
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" name="first_name" maxlength="30" class="form-control" placeholder="First Name" id="id_first_name">
                  </div>
                  <div class="form-group">
                    <input type="text" name="last_name" maxlength="150" class="form-control" placeholder="Last Name" title="" id="id_last_name">
                  </div>
                  <div class="form-group">
                    <input type="email" name="email" maxlength="200" class="form-control" placeholder="Email" required="" id="id_email">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" name="phone_no" maxlength="13" class="form-control" placeholder="Phone No" required="" id="id_phone_no">
                  </div>
                  <div class="form-group">
                    <input type="password" name="password1" class="form-control" placeholder="Password" required="" id="id_password1">
                  </div>
                  <div class="form-group">
                    <input type="password" name="password2" class="form-control" placeholder="Password confirmation" required="" id="id_password2">
                  </div>
                  <input type="submit" class="btnRegister"  value="Register"/>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block custom_js %}
  <script src="{% static 'js/jquery.easing.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="{% static 'js/contactform.js' %}"></script>
{% endblock %}