accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from accounts import views
from django.urls import path



app_name='accounts'

urlpatterns = [
    path('password_reset/', auth_views.PasswordResetView.as_view(), {'template_name': "registration/password_reset_form.html"}, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView,{'template_name': "registration/password_reset_done.html"},name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView,{'template_name': "registration/password_reset_confirm.html"},name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView,{'template_name': "registration/password_reset_complete.html"},name='password_reset_complete'),
    url(r'^signup/$', views.signup, name='signup'),
    path('show_data/', views.show_data, name='show_data'),
    path('pass_value/', views.pass_value, name='pass_value'),
    path('home/',views.Homepage.as_view(),name='home'),
    path('fetch_data/', views.fetch_data, name='fetch_data'),
    path('add_batch/',views.AddBatch.as_view(),name='add_batch'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'logout/$',auth_views.LogoutView.as_view(next_page='index'),name = 'logout'),    
]

time_table/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from accounts import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.CustomLoginView.as_view(),name='index'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('account/',include('django.contrib.auth.urls')),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/imagehover.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/my.css' %}">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">

    <!--bootstrap js -->
    <script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'ajax/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="  crossorigin="anonymous"></script>

    {% block extrascript %}

    {% endblock %}

    {% block extra_cdn %}

    {% endblock %}

    <meta charset="utf-8">

    <title>
      {% block title %}

      {% endblock %}
    </title>
    </head>
    <body>

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark primary-color myregister">

        <!-- Navbar brand -->
        <a class="navbar-brand" href="">Time Table</a>

        <!-- Collapse button -->

        <!-- Collapsible content -->
        <div class="navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:home' %}"><font style="color: white;">Home</font></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://iiitu.ac.in/"><font style="color: white;">IIIT Una</font></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}"><font style="color: white;">Admin</font></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:pass_value' %}"><font style="color: white;">Show Timetable</font></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}"><font style="color: white;">Logout</font></a>
            </li>
              {% endif %}

            <!-- Dropdown -->

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->
      </nav>
      <!--/.Navbar-->
      {% block body %}

      {% endblock %}

      {% block custom_js %}

      {% endblock %}
    </body>
  </html>